"""add company contact and legal fields for document branding

Revision ID: 46acf4511f7b
Revises: 1de1a1ef3bc2
Create Date: 2026-08-29 08:35:42.045748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46acf4511f7b'
down_revision: Union[str, None] = '1de1a1ef3bc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('phone', sa.String(length=30), nullable=True))
    op.add_column('company', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('company', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('company', sa.Column('cin_number', sa.String(length=30), nullable=True))
    op.add_column('company', sa.Column('registered_address', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'registered_address')
    op.drop_column('company', 'cin_number')
    op.drop_column('company', 'website')
    op.drop_column('company', 'email')
    op.drop_column('company', 'phone')
    # ### end Alembic commands ###
