"""add payslip_number, employee bank_name, offer and relieving letter records

Revision ID: 5e11c3f683c1
Revises: 46acf4511f7b
Create Date: 2026-08-29 10:17:25.029841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e11c3f683c1'
down_revision: Union[str, None] = '46acf4511f7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offer_letter_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('candidate_name', sa.String(length=255), nullable=False),
    sa.Column('candidate_address', sa.Text(), nullable=True),
    sa.Column('designation_id', sa.UUID(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('reporting_to_id', sa.UUID(), nullable=True),
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('employment_type', sa.String(length=20), nullable=False),
    sa.Column('salary_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_frequency', sa.String(length=20), nullable=True),
    sa.Column('bonus_details', sa.Text(), nullable=True),
    sa.Column('other_benefits', sa.Text(), nullable=True),
    sa.Column('acceptance_deadline', sa.Date(), nullable=True),
    sa.Column('hr_contact_name', sa.String(length=255), nullable=True),
    sa.Column('hr_contact_email', sa.String(length=255), nullable=True),
    sa.Column('employee_id', sa.UUID(), nullable=True),
    sa.Column('generated_by_employee_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['designation_id'], ['designation.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['generated_by_employee_id'], ['employee.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reporting_to_id'], ['employee.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offer_letter_record_company_id'), 'offer_letter_record', ['company_id'], unique=False)
    op.create_table('relieving_letter_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('last_working_date', sa.Date(), nullable=False),
    sa.Column('custom_paragraph', sa.Text(), nullable=True),
    sa.Column('generated_by_employee_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_by_employee_id'], ['employee.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relieving_letter_record_company_id'), 'relieving_letter_record', ['company_id'], unique=False)
    op.create_index(op.f('ix_relieving_letter_record_employee_id'), 'relieving_letter_record', ['employee_id'], unique=False)
    op.alter_column('company', 'phone',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.add_column('employee', sa.Column('bank_name', sa.String(length=150), nullable=True))
    op.add_column('payslip', sa.Column('payslip_number', sa.String(length=30), nullable=True))
    op.create_unique_constraint('uq_payslip_company_number', 'payslip', ['company_id', 'payslip_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_payslip_company_number', 'payslip', type_='unique')
    op.drop_column('payslip', 'payslip_number')
    op.drop_column('employee', 'bank_name')
    op.alter_column('company', 'phone',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.drop_index(op.f('ix_relieving_letter_record_employee_id'), table_name='relieving_letter_record')
    op.drop_index(op.f('ix_relieving_letter_record_company_id'), table_name='relieving_letter_record')
    op.drop_table('relieving_letter_record')
    op.drop_index(op.f('ix_offer_letter_record_company_id'), table_name='offer_letter_record')
    op.drop_table('offer_letter_record')
    # ### end Alembic commands ###
