"""018_company_subdomain_not_null

Revision ID: 5ef7a4f723e8
Revises: b42319f325c5
Create Date: 2026-09-03 08:30:03.980417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ef7a4f723e8'
down_revision: Union[str, None] = 'b42319f325c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company', 'subdomain',
               existing_type=sa.VARCHAR(length=63),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company', 'subdomain',
               existing_type=sa.VARCHAR(length=63),
               nullable=True)
    # ### end Alembic commands ###