"""017_company_subdomain

Revision ID: b42319f325c5
Revises: 5e11c3f683c1
Create Date: 2026-09-03 07:56:45.084724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b42319f325c5'
down_revision: Union[str, None] = '5e11c3f683c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('recipient_employee_id', sa.UUID(), nullable=False),
    sa.Column('actor_employee_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_employee_id'], ['employee.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_employee_id'], ['employee.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_actor_employee_id'), 'notification', ['actor_employee_id'], unique=False)
    op.create_index(op.f('ix_notification_company_id'), 'notification', ['company_id'], unique=False)
    op.create_index(op.f('ix_notification_is_read'), 'notification', ['is_read'], unique=False)
    op.create_index(op.f('ix_notification_recipient_employee_id'), 'notification', ['recipient_employee_id'], unique=False)
    op.create_index(op.f('ix_notification_type'), 'notification', ['type'], unique=False)
    op.add_column('company', sa.Column('subdomain', sa.String(length=63), nullable=True))
    op.create_index(op.f('ix_company_subdomain'), 'company', ['subdomain'], unique=True)
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_subdomain'), table_name='company')
    op.drop_column('company', 'subdomain')
    op.drop_index(op.f('ix_notification_type'), table_name='notification')
    op.drop_index(op.f('ix_notification_recipient_employee_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_is_read'), table_name='notification')
    op.drop_index(op.f('ix_notification_company_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_actor_employee_id'), table_name='notification')
    op.drop_table('notification')
    # ### end Alembic commands ###